name: CI/CD - Build and Push Container Image

# Se ejecuta en cada push a la rama 'main'
on:
    push:
        branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Inicia sesión en el GitHub Container Registry (GHCR)
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # 3. Construye y sube la imagen del contenedor
      - name: Build and push container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest
          containerfiles: |
            ./Containerfile
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      # 4. Transforma el nombre de la imagen a minúsculas para la URL
      - name: Convert image name to lowercase
        id: image-case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ steps.build-image.outputs.image-with-tag }}

      # 5. Muestra la URL de la imagen publicada
      - name: Print image URL
        run: echo "Image pushed to ${{ steps.image-case.outputs.lowercase }}"